      - name: Build kernel
        run: |
          make ARCH=arm64 clean mrproper
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- vendor/haydn-qgki_defconfig

          ./scripts/config --set-str CONFIG_LOCALVERSION "-${{ env.KERNEL_NAME }}"
          ./scripts/config -e CONFIG_KPM
          ./scripts/config -e CONFIG_KALLSYMS_ALL
          ./scripts/config -e CONFIG_MODULES

          # 强制关掉所有警告变错误 + 放开栈帧
          ./scripts/config -d CONFIG_WERROR
          ./scripts/config -d CONFIG_WERROR_FRAME_WARN
          ./scripts/config --set-val CONFIG_FRAME_WARN 16384
          ./scripts/config -d CONFIG_SCHED_STACK_END_CHECK

          # 编译时强制忽略警告
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
            KBUILD_CFLAGS="-Wno-frame-larger-than=" \
            -j$(nproc)
